apiVersion: v1
kind: Namespace
metadata:
  name: demo-backend-boot
---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend-boot-nodeport
  namespace: demo-backend-boot
spec:
  selector:
    app: demo-backend-boot-app
  ports:
  - protocol: TCP
    port: 8080 # Cluster 내부에서 사용하는 포트
    targetPort: 8080 # pod 입장에서 자기 자신을 노출한 포트
    nodePort: 30080 # 외부에서 접속하기 위해 사용되는 포트
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend-boot-app
  namespace: demo-backend-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-backend-boot-app
  template:
    metadata:
      labels:
        app: demo-backend-boot-app
    spec:
      containers:
      - name: demo-backend-boot-app
        image: chagchagchag/minikube-example-boot:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080