---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-server-clusterip
  name: argocd-server-clusterip
  namespace: argocd
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server