apiVersion: v1
kind: Service
metadata:
  name: minikube-example-boot-plaindockerfile
  namespace: minikube-example-boot-plaindockerfile
  labels:
    app: minikube-example-boot-plaindockerfile
spec:
  selector:
    app: minikube-example-boot-plaindockerfile
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30090
  type: NodePort